### ISSUE TITLE
Build fails unless BINOWN & friends are set

### ISSUE THREAD

**Issue by moyix** [ctdk/bsdgames-osx#2]
It looks like the default owner for install is set to `brew` using current `bsdmake` from Homebrew (on 10.10).

I eventually fixed it by manually setting all of the following (some of the later ones may not be strictly necessary):

    export BINOWN=moyix
    export LIBOWN=moyix
    export MANOWN=moyix
    export SHAREOWN=moyix
    export DOCOWN=moyix
    export INFOOWN=moyix
    export NLSOWN=moyix
    export INCOWN=moyix

Here's a gist of the failed compilation:

https://gist.github.com/anonymous/4408ca396143522f2cda

**Comment by sukima** [comment]
I can confirm this is indeed a problem with a fresh brew install:

```console
$ brew install bsdgames
==> Installing bsdgames from sukima/homebrew-fun
==> Downloading https://github.com/ctdk/bsdgames-osx/archive/bsdgames-osx-2.19.3.tar.gz
######################################################################## 100.0%
==> bsdmake PREFIX=/usr/local/Cellar/bsdgames/2.19.3 VARDIR=/usr/local/var/games
==> bsdmake install PREFIX=/usr/local/Cellar/bsdgames/2.19.3 VARDIR=/usr/local/var/games

Stop in /private/tmp/bsdgames-EgsCbf/bsdgames-osx-bsdgames-osx-2.19.3/adventure.
*** Error code 1

Stop in /private/tmp/bsdgames-EgsCbf/bsdgames-osx-bsdgames-osx-2.19.3.
couldn't understand kern.osversion `14.1.0'

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/sukima/homebrew-fun/issues
```

Mac OS X Yosemite: 10.10.2 (14C1514)

**Comment by sukima** [comment]
I'm sorry to nit-pick but are you still running < 10.10 four months now? I've been wanting bsd-games in homebrew for almost 5 years now. I even attempted to submit my own but the patches from macports when submitted to homebrew was too much and they nixed the idea out right.

**Comment by ctdk** [comment]
I am still running 10.9 (I've been very busy, and haven't wanted to disturb my dev environment yet and kept putting it off), but I did determine a while back that it's not actually the code here that's the problem, but the brew formula at https://gist.github.com/ctdk/5938940 - it built fine when running bsdmake by hand.

Setting up homebrew on my kids' machine will be the fastest way to do this, I think. I'll try and get that turned around as soon as I can.

**Comment by sukima** [comment]
How can I help?

**Comment by ctdk** [comment]
I was finally able to circle back to this (I was head down wrapping up at my old job after 11 years, and spent six weeks getting everything ready for my departure), and found that someone has already forked the homebrew formula and updated it for Yosemite here: https://gist.github.com/bartdorsey/908002f74f1870b3135a.

I've tested it, and it works. Looks like the problem's solved now.

**Comment by kristopherjohnson** [comment]
For anyone who doesn't want to figure out how to install and maintain the homebrew formula: You can build and install from source on OS X 10.11 El Capitan by installing bsdmake from Homebrew (`brew install bsdmake`) and executing these commands:

    git clone git@github.com:ctdk/bsdgames-osx.git
    cd bsdgames-osx.git
    bsdmake
    sudo BINOWN=$(whoami) SHAREOWN=$(whoami) PREFIX=/usr/local bsdmake install
