### ISSUE TITLE
Install on 10.6

### ISSUE THREAD

**Issue by excaliware** [ctdk/bsdgames-osx#4]
Thank you for porting the games. I could build it on 10.6 only after adding "CC=clang" (not "CC=clang bsdmake") to Makefile.inc. Also, the 'sudo bsdmake install' failed during the installation of the game 'ching', so I had to remove it from the Makefile to successfully install the games.

**Comment by ctdk** [comment]
I think I had already moved on from 10.6 by the time I started working on this. In re: "CC=clang", that might not be necessary on 10.6, and what I meant was that you needed to have "CC=clang" before "bsdmake" when building, like so:

`CC=clang bsdmake`

Unfortunately I can't easily test it myself, so I'm glad you were able to figure it out. Sorry about `ching` failing - ISTR I had to beat that about the head and shoulders to build on some later version of OS X, and it may have broken it for pre-Lion versions.
